### PR TITLE
Open dialog when clicking mention

### PR DESCRIPTION
**Pull request by nalanart**
Take a look Philippe, it's working fine for me

### CODE REVIEW

**Comment by nalanart** [comment]
Only thing is refreshing or linking to the url with the mention id won't open it up again. I'll keep digging

**Comment by jessdesr** [comment]
Will this work for explicitly navigating to the url for the mention dialog (like when you share the url with someone else)?

**Comment by nalanart** [comment]
haven't found a way yet. But looking at the reddit example, if we click a post, it opens a dialog with the post inside it. And if we were to link it, it would link to the page of the post. So it would make sense if the mention had a page for itself as well, right?

**Comment by nalanart** [comment]
> haven't found a way yet. But looking at the reddit example, if we click a post, it opens a dialog with the post inside it. And if we were to link it, it would link to the page of the post. So it would make sense if the mention had a page for itself as well, right?

What I mean is, linking a post that was opened from the home page would link to the page where the post is contained. It doesn't link to the home page with the dialog open, which is what we are trying to do right now. So should we just create a page for single mentions and have that rendered in the dialog as well?

**Comment by Jovialiste82** [comment]
Hey @nalanart , I think your solution helps greatly here! At least now we can display the dialog with its own URL and navigate back to the Mention when we close it. But I think we can't get around having a dedicated route if we want to be able to share it with someone, what do you think ? Maybe there's a way to do both (open the dialog your way and having a dedicated route for whomever uses the link), i'm going to dig further in that direction.

**Comment by Jovialiste82** [comment]
Finally ! I think it's working guys ! Can you go to my draft PR and test it on your end ? Thx again Alan ! I was really hitting a roadblock here. While waiting for your confirmation that it works too for you, I'll start taking care of the styling and cleaning up the code.

**Comment by nalanart** [comment]
> Hey @nalanart , I think your solution helps greatly here! At least now we can display the dialog with its own URL and navigate back to the Mention when we close it. But I think we can't get around having a dedicated route if we want to be able to share it with someone, what do you think ? Maybe there's a way to do both (open the dialog your way and having a dedicated route for whomever uses the link), i'm going to dig further in that direction.

Agreed! I think a dedicated route for sharing would be a good alternative.

**Pull request closed without merging**
