### PR TITLE
Scraping new york times

### PR DESCRIPTION
**Pull request by GuohaoOuyang**
check this out, guys

### CODE REVIEW

**Comment by dproc96** [comment]
When I was trying to test this I ran into two errors that don't appear to be related to your code here but should be addressed. On loading the page, I got the error that `keyword` referenced on line 74 of Mention.js is not defined. I commented that out to test the scraping at sign up and my server crashed with this error
```zsh
/Users/danproctor/Documents/code/coop/team-dolphin/server/models/userModel.js:57
  return await this.distinct("name").flat();
                                     ^

TypeError: this.distinct(...).flat is not a function
    at Function.userSchema.statics.getAllCompanies (/Users/danproctor/Documents/code/coop/team-dolphin/server/models/userModel.js:57:38)
    at Queue.<anonymous> (/Users/danproctor/Documents/code/coop/team-dolphin/server/utils/jobHandler.js:67:12)
    at node:internal/util:325:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:311:12)
    at Queue.processJob (/Users/danproctor/Documents/code/coop/team-dolphin/server/node_modules/bull/lib/queue.js:1088:22)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[nodemon] app crashed - waiting for file changes before starting...
```
Like I said, I don't think these are related to this PR, but they should be addressed before this branch can be properly tested.

**Comment by GuohaoOuyang** [comment]
Thank you, Dan!I will Work on that.

**Comment by GuohaoOuyang** [comment]
repeated handleTaskQueues and handleIndividualCompany when signup tested. 
fixed keyword highlight bug, now display correct highlight

**Comment by GuohaoOuyang** [comment]
> When I was trying to test this I ran into two errors that don't appear to be related to your code here but should be addressed. On loading the page, I got the error that `keyword` referenced on line 74 of Mention.js is not defined. I commented that out to test the scraping at sign up and my server crashed with this error
> 
> ```shell
> /Users/danproctor/Documents/code/coop/team-dolphin/server/models/userModel.js:57
>   return await this.distinct("name").flat();
>                                      ^
> 
> TypeError: this.distinct(...).flat is not a function
>     at Function.userSchema.statics.getAllCompanies (/Users/danproctor/Documents/code/coop/team-dolphin/server/models/userModel.js:57:38)
>     at Queue.<anonymous> (/Users/danproctor/Documents/code/coop/team-dolphin/server/utils/jobHandler.js:67:12)
>     at node:internal/util:325:7
>     at new Promise (<anonymous>)
>     at bound  (node:internal/util:311:12)
>     at Queue.processJob (/Users/danproctor/Documents/code/coop/team-dolphin/server/node_modules/bull/lib/queue.js:1088:22)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> [nodemon] app crashed - waiting for file changes before starting...
> ```
> 
> Like I said, I don't think these are related to this PR, but they should be addressed before this branch can be properly tested.

The errors has been fixed

**Review by nalanart — APPROVED** [review]
Good job on fixing the highlighting bug.  The scraper seems to be working good as well!

**Comment by GuohaoOuyang** [comment]
> Good job on fixing the highlighting bug. The scraper seems to be working good as well!
Cool, thanks!

**Pull request merged**
